"""initial_consolidated_schema

Revision ID: 8499e1630da3
Revises: 
Create Date: 2026-02-19 15:21:57.408994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8499e1630da3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvases',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sa.Text(), server_default='', nullable=False),
    sa.Column('topic', sa.Text(), server_default='', nullable=False),
    sa.Column('working_title', sa.Text(), server_default='', nullable=False),
    sa.Column('abstract', sa.Text(), server_default='', nullable=False),
    sa.Column('keywords', sa.Text(), server_default='[]', nullable=False),
    sa.Column('stage', sa.Text(), server_default='explore', nullable=False),
    sa.Column('refined_markdown', sa.Text(), server_default='', nullable=False),
    sa.Column('identified_gaps', sa.Text(), server_default='[]', nullable=False),
    sa.Column('user_directives', sa.Text(), server_default='[]', nullable=False),
    sa.Column('research_brief', sa.Text(), server_default='{}', nullable=False),
    sa.Column('research_insights', sa.Text(), server_default='[]', nullable=False),
    sa.Column('skip_draft_review', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skip_refine_review', sa.Integer(), server_default='0', nullable=False),
    sa.Column('archived', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_id', sa.Text(), server_default='', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crossref_cache',
    sa.Column('normalized_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doi', sa.Text(), server_default='', nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('authors', sa.Text(), server_default='', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('normalized_title')
    )
    op.create_table('deep_research_jobs',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), server_default='', nullable=False),
    sa.Column('canvas_id', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('current_stage', sa.Text(), server_default='', nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('request_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('result_markdown', sa.Text(), server_default='', nullable=False),
    sa.Column('result_citations', sa.Text(), server_default='[]', nullable=False),
    sa.Column('result_dashboard', sa.Text(), server_default='{}', nullable=False),
    sa.Column('total_time_ms', sa.Float(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('deep_research_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_dr_jobs_created_at', ['created_at'], unique=False)

    op.create_table('ingest_jobs',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collection', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('total_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('processed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_chunks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_upserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_file', sa.Text(), server_default='', nullable=False),
    sa.Column('current_stage', sa.Text(), server_default='', nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('finished_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_ingest_jobs_created_at', ['created_at'], unique=False)

    op.create_table('paper_metadata',
    sa.Column('paper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doi', sa.Text(), server_default='', nullable=False),
    sa.Column('normalized_doi', sa.Text(), server_default='', nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('normalized_title', sa.Text(), server_default='', nullable=False),
    sa.Column('authors', sa.Text(), server_default='', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), server_default='', nullable=False),
    sa.Column('extra', sa.Text(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('paper_id')
    )
    with op.batch_alter_table('paper_metadata', schema=None) as batch_op:
        batch_op.create_index('idx_pm_ndoi', ['normalized_doi'], unique=False)
        batch_op.create_index('idx_pm_ntitle', ['normalized_title'], unique=False)

    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), server_default='', nullable=False),
    sa.Column('file_path', sa.Text(), server_default='', nullable=False),
    sa.Column('file_size', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enrich_tables_enabled', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enrich_figures_enabled', sa.Integer(), server_default='0', nullable=False),
    sa.Column('table_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('figure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('table_success', sa.Integer(), server_default='0', nullable=False),
    sa.Column('figure_success', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='done', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection', 'paper_id', name='uq_papers_collection_paper')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index('idx_papers_collection', ['collection'], unique=False)

    op.create_table('sessions',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canvas_id', sa.Text(), server_default='', nullable=False),
    sa.Column('stage', sa.Text(), server_default='explore', nullable=False),
    sa.Column('rolling_summary', sa.Text(), server_default='', nullable=False),
    sa.Column('summary_at_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preferences_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('password_hash', sa.Text(), server_default='', nullable=False),
    sa.Column('role', sa.Text(), server_default='user', nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('working_memory',
    sa.Column('canvas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('meta_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('canvas_id')
    )
    op.create_table('canvas_citations',
    sa.Column('canvas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cite_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citation_id', sa.Text(), server_default='', nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('authors_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('bibtex', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.PrimaryKeyConstraint('canvas_id', 'cite_key')
    )
    op.create_table('canvas_versions',
    sa.Column('canvas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.PrimaryKeyConstraint('canvas_id', 'version_number')
    )
    op.create_table('deep_research_gap_supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_id', sa.Text(), nullable=False),
    sa.Column('gap_text', sa.Text(), server_default='', nullable=False),
    sa.Column('supplement_type', sa.Text(), server_default='material', nullable=False),
    sa.Column('content_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('consumed_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['deep_research_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deep_research_gap_supplements', schema=None) as batch_op:
        batch_op.create_index('idx_dr_gap_supplements_job_section', ['job_id', 'section_id'], unique=False)

    op.create_table('deep_research_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_id', sa.Text(), server_default='', nullable=False),
    sa.Column('insight_type', sa.Text(), server_default='gap', nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('source_context', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['deep_research_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deep_research_insights', schema=None) as batch_op:
        batch_op.create_index('idx_dr_insights_job_id', ['job_id'], unique=False)

    op.create_table('deep_research_job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['deep_research_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deep_research_job_events', schema=None) as batch_op:
        batch_op.create_index('idx_dr_job_events_job_id_id', ['job_id', 'id'], unique=False)

    op.create_table('deep_research_resume_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_instance', sa.Text(), server_default='', nullable=False),
    sa.Column('source', sa.Text(), server_default='review', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['deep_research_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deep_research_resume_queue', schema=None) as batch_op:
        batch_op.create_index('idx_dr_resume_queue_owner_status', ['owner_instance', 'status', 'created_at'], unique=False)
        batch_op.create_index('idx_dr_resume_queue_status_created', ['status', 'created_at'], unique=False)

    op.create_table('deep_research_section_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), server_default='approve', nullable=False),
    sa.Column('feedback', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['deep_research_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'section_id', name='uq_dr_section_reviews')
    )
    op.create_table('draft_blocks',
    sa.Column('canvas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_md', sa.Text(), server_default='', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('used_fragment_ids', sa.Text(), server_default='[]', nullable=False),
    sa.Column('used_citation_ids', sa.Text(), server_default='[]', nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.PrimaryKeyConstraint('canvas_id', 'section_id')
    )
    op.create_table('ingest_job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('data_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ingest_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_job_events', schema=None) as batch_op:
        batch_op.create_index('idx_ingest_job_events_job_id_id', ['job_id', 'id'], unique=False)

    op.create_table('outline_sections',
    sa.Column('canvas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='todo', nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.PrimaryKeyConstraint('canvas_id', 'id')
    )
    op.create_table('turns',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('evidence_pack_id', sa.Text(), nullable=True),
    sa.Column('canvas_patch', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('session_id', 'turn_index')
    )
    op.create_table('user_projects',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('canvas_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'canvas_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_projects')
    op.drop_table('turns')
    op.drop_table('outline_sections')
    with op.batch_alter_table('ingest_job_events', schema=None) as batch_op:
        batch_op.drop_index('idx_ingest_job_events_job_id_id')

    op.drop_table('ingest_job_events')
    op.drop_table('draft_blocks')
    op.drop_table('deep_research_section_reviews')
    with op.batch_alter_table('deep_research_resume_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_dr_resume_queue_status_created')
        batch_op.drop_index('idx_dr_resume_queue_owner_status')

    op.drop_table('deep_research_resume_queue')
    with op.batch_alter_table('deep_research_job_events', schema=None) as batch_op:
        batch_op.drop_index('idx_dr_job_events_job_id_id')

    op.drop_table('deep_research_job_events')
    with op.batch_alter_table('deep_research_insights', schema=None) as batch_op:
        batch_op.drop_index('idx_dr_insights_job_id')

    op.drop_table('deep_research_insights')
    with op.batch_alter_table('deep_research_gap_supplements', schema=None) as batch_op:
        batch_op.drop_index('idx_dr_gap_supplements_job_section')

    op.drop_table('deep_research_gap_supplements')
    op.drop_table('canvas_versions')
    op.drop_table('canvas_citations')
    op.drop_table('working_memory')
    op.drop_table('user_profiles')
    op.drop_table('sessions')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index('idx_papers_collection')

    op.drop_table('papers')
    with op.batch_alter_table('paper_metadata', schema=None) as batch_op:
        batch_op.drop_index('idx_pm_ntitle')
        batch_op.drop_index('idx_pm_ndoi')

    op.drop_table('paper_metadata')
    with op.batch_alter_table('ingest_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_ingest_jobs_created_at')

    op.drop_table('ingest_jobs')
    with op.batch_alter_table('deep_research_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_dr_jobs_created_at')

    op.drop_table('deep_research_jobs')
    op.drop_table('crossref_cache')
    op.drop_table('canvases')
    # ### end Alembic commands ###
